### ISSUE TITLE
Alternative Perspective journal entry

### ISSUE THREAD

**Issue by ThwartAbyss54** [ixanza/tranquility#12]
**Describe the bug**
The journal entry for alternative perspective to examine the room doesnt pop markers onto the chest in front of the bed, drawer, wardrobe, or strongbox and doesnt go away even after completing to bleak falls barrow.

An edit from the discord, possibly the extra options from New Beginnings arent showing up?

**To Reproduce**
start a new game and play through

**Expected behavior**
From what i remember it shows map marker arrows on the draw, wardrobe, chest in front of the bed, and strongbox on the table. Should also complete the journal entry after you sleep in the bed to start the main quest?

**Screenshots**

![139](https://user-images.githubusercontent.com/41197987/150985789-5e9b3a40-14a6-4229-b17c-471535bbf1db.png)

**Modlist version**
1.2.1

**Did you add any additional mods?**
https://www.nexusmods.com/skyrimspecialedition/mods/50682

**Comment by ixanza** [comment]
Fixed in 1.2.2
