### ISSUE TITLE
Candles, smoke from smelters, enchanting altar fps

### ISSUE THREAD

**Issue by ThwartAbyss54** [ixanza/tranquility#13]
**Describe the bug**
Looking at candles, the smoke coming off forges and smelters, enchanting tables causes a lot of fps loss. From solid 60 to 30s on a 3060ti. I assume its something to do with particles?

**To Reproduce**
Stare at the pretty lights lol

**Expected behavior**
A small loss would be fine but not 30+ fps lol

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, take a screenshot of `You are Here` MCM Option from DynDOLOD as well as a screenshot of the world map.

**Modlist version**
1.2.1

**Did you add any additional mods?**
https://www.nexusmods.com/skyrimspecialedition/mods/50682

**Comment by ixanza** [comment]
Fixed in 1.2.2
