### ISSUE TITLE
Does not WORK, won't download last files.

### ISSUE THREAD

**Issue by EASK8ER52** [ixanza/tranquility#15]
I keep getting an issue where it won't download the last files. It keeps trying to find alternative links for them but it can't. And as such it won't move out of the failed screen and install it. It says "Unable to download Data_ccasvsse001-almsivi.bsa" and others like it. They are Skyrim Anniversary DLC. It's annoying because I already have them, not sure why it is trying to download them.

**Comment by ixanza** [comment]
Delete that and redownload frm the creation club store. the creation was updated and needs to be redownloaded
