### ISSUE TITLE
Forsworn starting option

### ISSUE THREAD

**Issue by Kyle-sys** [ixanza/tranquility#7]
**Describe the bug**
When attempting to exit to Skyrim, I was presented with a abnormally long or infinite loading screen.

**To Reproduce**
1. Upon loading the game, select the Forsworn starting option.
2. Then attempt to exit to Skyrim.

**Expected behavior**
For the game to load normally. I tried a couple of the other starting options and they seem to work normally.

**Modlist version**
Tranquility 1.0.0

**Did you add any additional mods?**
No, the only thing I did was change SSE Display tweaks to full screen (disabled borderless and enabled full screen).

**Comment by ixanza** [comment]
Hey. There appears to be an issue with the base game BSAs when WJ installs the list. I'll fix this in the next update however you can temporarily fix this by overwriting the BSAs in Tranquility/Stock Game/data with the ones in steamapps/common/Skyrim Special Edition/data.

**Comment by Kyle-sys** [comment]
I see. Yup that seems to of worked. Nice.

**Comment by ixanza** [comment]
should be fixed in 1.1.0
