### ISSUE TITLE
alternate perspective script breaks CC quest start conditions

### ISSUE THREAD

**Issue by criminaltango44** [ixanza/tranquility#8]
specifically, it overwrites the "ccstartafterchargen" script which was updated by beth after AE, so now you get all the letters from quests at the beginning.

also https://www.nexusmods.com/skyrimspecialedition/mods/61004

it's my mod and you're already using the 1st version in the modlist but it got updated with an MCM, also the scripts I mentioned above are basically not used anymore.

**Comment by ixanza** [comment]
Thanks for this. I'll have a look and implement your update :D

**Comment by ixanza** [comment]
hey @criminaltango44 . There's a conflict with enabling the bosses from Knights of the Nine and Lawbringer. Let me know if resolving it this way is correct. I duplicated your XMarker with the Global Condition on enabling it and added Lawbringer's Location Reference from its own Xmarker on the same NPC and assigned that to the 2 NPCs in KOTN. I'm not quite used to Xmarkers enabling initially disabled stuff.

**Comment by criminaltango44** [comment]
that should work but in my testing I found that enable parents are often wonky and don't work for stupid reasons like 1 script having priority over the other, so you'll have to test it. I'm not sure how Lawbringer works there exactly so I'll check that out soon
