### ISSUE TITLE
Some weapons do not have icons

### ISSUE THREAD

**Issue by Fjodik** [ixanza/tranquility#9]
**Describe the bug**
Certain weapons from Animated Armoury do not have corresponding class icon under SkyUI (see image).

**To Reproduce**
Check the weapon under SkyUI.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, take a screenshot of `You are Here` MCM Option from DynDOLOD as well as a screenshot of the world map.

**Modlist version**
1.1.0

**Did you add any additional mods?**
No

![ScreenShot109](https://user-images.githubusercontent.com/63248466/148651398-9659d6a6-ecc3-462a-8f87-fbaef295c458.jpg)
![ScreenShot108](https://user-images.githubusercontent.com/63248466/148651399-8a068bcb-8fce-41aa-aafb-47c5a17bda18.jpg)

**Comment by ixanza** [comment]
ah right I knew I forgot something. Thanks. Will be fixed in the next version. If you wanna fix this yourself install https://www.nexusmods.com/skyrimspecialedition/mods/37231? and load it above body slots in the User Interface Section

**Comment by ixanza** [comment]
Fixed in 1.1.1
